import { Question, User } from '../types';

export const ADMIN_EMAIL = 'pandit.alap@gmail.com';

// No mock or temporary users - users will only be populated from actual registered accounts in the database
export const INITIAL_USERS: User[] = [];

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q_cs_001',
    text: 'What is the average time complexity of searching for an element in a balanced Binary Search Tree (such as an AVL or Red-Black Tree)?',
    options: {
      A: 'O(1)',
      B: 'O(log n)',
      C: 'O(n)',
      D: 'O(n log n)',
    },
    correctOption: 'B',
    subject: 'Computer Science',
    difficulty: 'Medium',
    tags: ['algorithms', 'data-structures', 'trees', 'complexity'],
    referenceExplanation: 'In a balanced binary search tree with n nodes, the height is bounded by O(log n), making lookup, insertion, and deletion operations O(log n) on average and worst-case.',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-05T11:20:00Z',
    updatedAt: '2026-08-05T11:20:00Z',
  },
  {
    id: 'q_cs_002',
    text: 'Which HTTP status code signifies that the client must authenticate itself to get the requested response?',
    options: {
      A: '401 Unauthorized',
      B: '403 Forbidden',
      C: '404 Not Found',
      D: '400 Bad Request',
    },
    correctOption: 'A',
    subject: 'Computer Science',
    difficulty: 'Easy',
    tags: ['web', 'http', 'networking', 'api'],
    referenceExplanation: 'HTTP 401 Unauthorized indicates that the request lacks valid authentication credentials for the target resource. (403 means authenticated but not permitted).',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-07T09:40:00Z',
    updatedAt: '2026-08-07T09:40:00Z',
  },
  {
    id: 'q_phy_001',
    text: 'Which physical principle explains why an ice skater spins faster when pulling their arms inward?',
    options: {
      A: 'Conservation of Linear Momentum',
      B: 'Conservation of Angular Momentum',
      C: 'Bernoulli\'s Principle',
      D: 'Archimedes\' Principle',
    },
    correctOption: 'B',
    subject: 'Physics',
    difficulty: 'Easy',
    tags: ['classical-mechanics', 'rotation', 'momentum', 'physics'],
    referenceExplanation: 'Angular momentum L = I * omega is conserved. Pulling the arms inward reduces the rotational inertia (I), forcing the angular velocity (omega) to increase.',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-12T15:00:00Z',
    updatedAt: '2026-08-12T15:00:00Z',
  },
  {
    id: 'q_phy_002',
    text: 'What phenomenon causes light to bend as it passes from air into water at an angle?',
    options: {
      A: 'Diffraction',
      B: 'Refraction',
      C: 'Polarization',
      D: 'Total Internal Reflection',
    },
    correctOption: 'B',
    subject: 'Physics',
    difficulty: 'Easy',
    tags: ['optics', 'waves', 'light'],
    referenceExplanation: 'Refraction is the change in direction of a wave passing from one medium to another caused by its change in speed, quantified by Snell\'s Law.',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-14T10:15:00Z',
    updatedAt: '2026-08-14T10:15:00Z',
  },
  {
    id: 'q_his_001',
    text: 'In which year did the Apollo 11 mission successfully land the first humans on the Moon?',
    options: {
      A: '1965',
      B: '1969',
      C: '1971',
      D: '1973',
    },
    correctOption: 'B',
    subject: 'World History',
    difficulty: 'Easy',
    tags: ['space', '20th-century', 'modern-history'],
    referenceExplanation: 'Neil Armstrong and Buzz Aldrin landed the Apollo 11 Lunar Module Eagle on the Moon on July 20, 1969.',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-18T13:00:00Z',
    updatedAt: '2026-08-18T13:00:00Z',
  },
  {
    id: 'q_his_002',
    text: 'Which ancient civilization constructed the city of Machu Picchu high in the Andes mountains?',
    options: {
      A: 'Aztec',
      B: 'Maya',
      C: 'Inca',
      D: 'Olmec',
    },
    correctOption: 'C',
    subject: 'World History',
    difficulty: 'Medium',
    tags: ['archaeology', 'ancient-civilizations', 'americas'],
    referenceExplanation: 'Machu Picchu was built in the 15th century by the Inca Empire, likely under the reign of Emperor Pachacuti.',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-22T08:50:00Z',
    updatedAt: '2026-08-22T08:50:00Z',
  },
  {
    id: 'q_cs_003',
    text: 'In relational databases, which normal form (NF) specifically eliminates transitive dependencies of non-prime attributes on candidate keys?',
    options: {
      A: 'First Normal Form (1NF)',
      B: 'Second Normal Form (2NF)',
      C: 'Third Normal Form (3NF)',
      D: 'Boyce-Codd Normal Form (BCNF)',
    },
    correctOption: 'C',
    subject: 'Computer Science',
    difficulty: 'Hard',
    tags: ['database', 'sql', 'normalization'],
    referenceExplanation: '3NF requires that the relation is in 2NF and that no non-prime attribute is transitively dependent on any candidate key.',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'q_math_001',
    text: 'What is the derivative of f(x) = ln(3x^2 + 1) with respect to x?',
    options: {
      A: '6x / (3x^2 + 1)',
      B: '1 / (3x^2 + 1)',
      C: '6 / (3x^2 + 1)',
      D: '3x / (3x^2 + 1)',
    },
    correctOption: 'A',
    subject: 'Mathematics',
    difficulty: 'Medium',
    tags: ['calculus', 'derivatives', 'chain-rule'],
    referenceExplanation: 'By the chain rule, d/dx[ln(u)] = (1/u) * u\'. Here u = 3x^2 + 1, so u\' = 6x, yielding f\'(x) = 6x / (3x^2 + 1).',
    contributorUid: 'usr_admin_alap',
    contributorName: 'Alap Pandit',
    contributorEmail: 'pandit.alap@gmail.com',
    createdAt: '2026-08-29T14:10:00Z',
    updatedAt: '2026-08-29T14:10:00Z',
  },
];
